name:                lecture-code
version:             0.1.0.0
license:             BSD3
author:              "Steven Wolfman"
maintainer:          "wolf@mail.ubc.ca"
description:         Setup for using repl.it in class

dependencies:
- base >= 4.7 && < 5
- random

executables:
  dummy:
    main: Main.hs
    source-dirs: .dummy

